volumes:
  rag_qa_local_postgres_data: {}
  rag_qa_local_postgres_data_backups: {}
  rag_qa_local_redis_data: {}
  pgvector_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: rag_qa_local_django
    container_name: rag_qa_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: rag_qa_local_postgres
    container_name: rag_qa_local_postgres
    volumes:
      - rag_qa_local_postgres_data:/var/lib/postgresql/data
      - rag_qa_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  pgvector:
    image: ankane/pgvector:0.5.1
    container_name: rag_qa_local_pgvector
    environment:
      - POSTGRES_HOST=pgvector
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - pgvector_data:/var/lib/postgresql/data

  redis:
    image: docker.io/redis:6
    container_name: rag_qa_local_redis
    
    volumes:
      - rag_qa_local_redis_data:/data
    

  celeryworker:
    <<: *django
    image: rag_qa_local_celeryworker
    container_name: rag_qa_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: rag_qa_local_celerybeat
    container_name: rag_qa_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: rag_qa_local_flower
    container_name: rag_qa_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
