# Generated by Django 5.0.10 on 2024-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Test', max_length=512),
            preserve_default=False,
        ),
    ]
