# Generated by Django 5.0.10 on 2024-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
