# Generated by Django 5.0.10 on 2024-12-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=2048)),
                ('answer_id', models.CharField(max_length=64)),
            ],
        ),
    ]
